// -----------------------------------------------------------------------------
// FIELD OPERATOR permission set (Section 4.9)
// Create/modify Daily Production documents and calculate net volumes. No
// posting rights. Default Role Center: Field Operator.
// -----------------------------------------------------------------------------
permissionset 70140 "FIELD OPERATOR"
{
    Caption = '- Field Operator';
    Assignable = true;

    Permissions = tabledata "Production Entry Header" = RIMD,
                  tabledata "Production Entry Line" = RIMD,
                  tabledata "Reservoir" = R,
                  tabledata "Reservoir Product Setup" = R,
                  tabledata "Date Range" = R,
                  page "Field Operator Role Center" = X,
                  page "Open Production Entries" = X,
                  page "Production Entry List" = X,
                  page "Production Entry Card" = X,
                  page "Production Entry Line" = X,
                  page "Date Range" = X,
                  codeunit "Production Entry Helper" = X,
                  codeunit "O&G BOE Conversion" = X,
                  tabledata "O&G Setup" = R,
                  tabledata "Dimension" = R,
                  tabledata "Dimension Value" = R,
                  tabledata "Dimension Set Entry" = R,
                  tabledata "Item" = R,
                  tabledata "Item Unit of Measure" = R,
                  tabledata "Unit of Measure" = R,
                  tabledata "Location" = R,
                  tabledata "Default Dimension" = R,
                  tabledata "Item Journal Template" = R,
                  tabledata "Item Journal Batch" = R,
                  tabledata "Gen. Business Posting Group" = R,
                  page "Reservoir List" = X,
                  page "Reservoir Card" = X,
                  page "Reservoir Product Setup" = X,
                  page "Dimension Value List" = X,
                  page "Dimension Set Entries" = X,
                  page "Item List" = X,
                  page "Item Units of Measure" = X,
                  page "Units of Measure" = X,
                  page "Location List" = X,
                  page "Open Production List" = X,
                  page "Posted Production Card" = X,
                  codeunit "Dimension Helper" = X,
                  codeunit "DimensionManagement" = X,
                  codeunit "Production Entry Guard" = X,
                  table "Production Entry Header" = X,
                  table "Production Entry Line" = X,
                  table "Reservoir" = X,
                  table "Reservoir Product Setup" = X,
                  table "Date Range" = X,
                  table "O&G Setup" = X,
                  tabledata "Depletion Worksheet" = R,
                  table "Depletion Worksheet" = X,
                  tabledata "Reserve Revision History" = R,
                  table "Reserve Revision History" = X,
                  page "Reserve Revision History" = X,
                  tabledata "Reserve Estimation Method" = R,
                  table "Reserve Estimation Method" = X,
                  page "Reserve Estimation Methods" = X,
                  tabledata User = R,
                  page "Reserve Estimator Users" = X,
                  codeunit "Reserve Estimation Mgt." = X,
                  tabledata "O&G Entity" = R,
                  table "O&G Entity" = X,
                  tabledata "Production Posting Link" = R,
                  table "Production Posting Link" = X,
                  tabledata "Production Ledger Link" = R,
                  table "Production Ledger Link" = X,
                  tabledata "No. Series" = R,
                  tabledata "General Ledger Setup" = R,
                  tabledata "Item Ledger Entry" = R,
                  tabledata "Item Application Entry" = R,
                  tabledata "Value Entry" = R,
                  tabledata "No. Series Line" = Rm,
                  codeunit "No. Series" = X,
                  codeunit "O&G Entity Mgt." = X,
                  codeunit "Production Posting Tracking" = X,
                  page "O&G Entities" = X,
                  page "Production Posting Links" = X,
                  tabledata "Production Dim. Correction" = R,
                  table "Production Dim. Correction" = X,
                  tabledata "Production Dim. Change" = R,
                  table "Production Dim. Change" = X,
                  codeunit "Production Entry Workflow" = X,
                  page "Production Dimension History" = X,
                  page "Production Dim. Change Card" = X,
                  page "Production Dimension Changes" = X,
                  tabledata "Depletion Ledger Link" = R,
                  table "Depletion Ledger Link" = X;
}
