#!/usr/bin/env python3
"""Static source/schema/logic checks. Does NOT execute AL on a BC server."""
from pathlib import Path
import json,re,sys
from decimal import Decimal, ROUND_HALF_UP
from schema_parser import fields
from lxml import etree as ET
R=Path(__file__).resolve().parents[1];V=R/'validation'
def rd(p):return (R/p).read_text()
checks=[]
def ck(n,v):checks.append({'check':n,'pass':bool(v)})
app=json.loads(rd('app.json'));ck('Version 1.0.13.0 / BC 26 / runtime 16 / NoImplicitWith',app['version']=='1.0.13.0' and app['application']=='26.0.0.0' and app['runtime']=='16.0' and 'NoImplicitWith' in app['features'])
base=json.loads(rd('validation/baseline-schema-v1.0.12.json'))
current={p.name:{i:{k:v for k,v in f.items() if k!='block'} for i,f in fields(p.read_text()).items()} for p in (R/'src/Tables').glob('*.al')}
ck('Every prior table and field retains ID/name/type/class',all(t in current and all(current[t].get(i)==f for i,f in fs.items()) for t,fs in base.items()))
als=list((R/'src').rglob('*.al'));src='\n'.join(p.read_text() for p in als)
objs=re.findall(r'^\s*(tableextension|pageextension|permissionset|codeunit|report|table|page|enum)\s+(\d+)\s',src,re.M)
ck('Object IDs unique and in assigned range',len(objs)==len({i for _,i in objs}) and all(70000<=int(i)<=75000 for _,i in objs))
ck('No client-owned tables 70012-70014 declared',not any(t=='table' and i in {'70012','70013','70014'} for t,i in objs))
ck('No DataClassification on FlowFields',all('DataClassification' not in f['block'] for p in (R/'src/Tables').glob('*.al') for f in fields(p.read_text()).values() if f['class']=='FlowField'))
h=rd('src/Tables/ProductionEntryHeader.Table.al');guard=rd('src/Codeunits/ProductionEntryGuard.Codeunit.al');track=rd('src/Codeunits/ProductionPostingTracking.Codeunit.al');rev=rd('src/Codeunits/ProductionReversalMgt.Codeunit.al');post=rd('src/Codeunits/PostDailyProduction.Codeunit.al');ent=rd('src/Codeunits/OGEntityMgt.Codeunit.al');own=rd('src/Codeunits/JVOwnershipMgt.Codeunit.al');jv=rd('src/Codeunits/JVCostAllocation.Codeunit.al');dep=rd('src/Codeunits/DepletionCalculation.Codeunit.al');roy=rd('src/Codeunits/RoyaltyCalculation.Codeunit.al');jnl=rd('src/Codeunits/JournalHelper.Codeunit.al');rsv=rd('src/Tables/Reservoir.Table.al')
ck('Modern No. Series API used, configured in O&G Setup','NumberSeries.TestAutomatic(OGSetup."Production Nos.")' in h and 'NumberSeries.GetNextNo(Rec."No. Series", WorkDate())' in h)
ck('Manual new production numbers rejected','if Rec."Document No." <> \'\' then' in h and 'numbers are automatic' in h)
ck('No number is allocated in a modal lookup/new-record dialog','GetNextNo' not in rd('src/Pages/ProductionEntryCard.Page.al') and 'GetNextNo' not in rd('src/Pages/ProductionCorrectionDialog.Page.al'))
ck('Historical number and source dimensions preserved by data guard','ValidateSystemMetadata(Rec, StoredHeader)' in guard and 'NewField.Number() in [17, 18, 19, 20, 21, 23]' in guard)
ck('Entity uses actual Global Dimension 1, not a hardcoded dimension name','GLSetup."Global Dimension 1 Code"' in ent and "const('ENTITY')" not in src)
ck('Entity mandatory on production send','EntityMgt.ValidateEntity(ProdHeader."Entity Code")' in post)
ck('Entity included in production dimension set','ProdHeader."Cost Center Code", \'\', ProdHeader."Entity Code")' in post)
ck('Legacy Entity not guessed from operator/default setup','no reliable Entity evidence' in ent and 'multiple Entities' in ent)
ck('New source journal lines carry a unique production link','Tracking.RegisterJournalLine(' in post and 'field(73000; "O&G Production Link No."' in rd('src/TableExtensions/OGItemJournalLink.TableExt.al'))
ck('Actual native item-ledger insert event tracked',"'OnAfterInsertItemLedgEntry'" in track and 'RecordLedger(ItemJournalLine."O&G Production Link No.", ItemLedgerEntry)' in track)
ck('Missing journal rows are not treated as proof of ledger posting','StateForDocument' in track and 'Inventory posting state must match the linked journal/ledger evidence' in guard)
ck('Native posting transactions are not committed by tracking','Commit(' not in track and 'Commit(' not in rev)
ck('Only verified fully pending source can be cancelled','<> "Production Posting State"::Pending' in rev and 'Tracking.ValidateMovement(JournalLine, Link)' in rev)
ck('Cancellation keeps source and audit; does not delete source/ledger records','Header.Cancelled := true' in rev and 'Header."Cancelled By" := UserSecurityId()' in rev and 'Header.Delete(' not in rev and 'Entry.Delete(' not in rev)
ck('Pending journal deletion protected outside cancellation',"'OnBeforeDeleteEvent'" in track and 'Use Cancel Pending Journal' in track)
ck('Partially posted/unknown sources blocked from full reversal','<> "Production Posting State"::Posted' in rev and 'Partially posted documents must be resolved' in rev)
ck('Reversal is a new auto-numbered, linked source','Reversal.Insert(true)' in rev and 'Reversal."Reverses Document No." := Original."Document No."' in rev)
ck('Reversal retains signed source BOE and immutable original','ReverseLine."BOE Quantity" := -OriginalLine."BOE Quantity"' in rev and 'Reversal."Total BOE" := -Original."Total BOE"' in rev)
ck('Corrected copy cannot silently duplicate an active replacement','Correction %1 already exists' in rev and 'Another active correction' in post)
ck('Cancellation removes operational BOE without changing posted flag','Cancelled = filter(false)' in rsv and 'Header.Posted := false' not in rev)
ck('Posted reversals restore BS&W before removing receipts',rev.index('// Restore original BS&W') < rev.index('// Remove the original receipts'))
ck('Reversal uses exact original cost-application references','Validate("Applies-from Entry", OriginalEntry."Entry No.")' in rev and 'Validate("Applies-to Entry", ApplyToEntry)' in rev)
ck('Own-loss restoration applications resolved at native posting','Link."Apply To Link No."' in track and 'ItemJournalLine.Validate("Applies-to Entry", LedgerLink."Item Ledger Entry No.")' in track)
ck('Tracking/reservations/warehouse/downstream use not bypassed',all(s in rev for s in ['Item."Item Tracking Code"','Entry."Reserved Quantity"','Location."Bin Mandatory"','downstream use outside']))
ck('Legacy ledger linking explicit and checks complete gross/loss totals','procedure LinkLegacyLedger' in rev and 'PositiveTotal - SourceLine.Quantity' in rev and 'NegativeTotal - (SourceLine.Quantity - SourceLine."Net Quantity")' in rev)
ck('No direct Item Jnl.-Post execution introduced by reversal','CODEUNIT.Run' not in rev and 'Codeunit "Item Jnl.-Post"' not in rev)
for name in ['DepletionWorksheet.Page.al','RoyaltyWorksheet.Page.al']:
 s=rd('src/Pages/'+name)
 ck(name+' prompt uses a temporary buffer','RangeRec: Record "Date Range" temporary;' in s and 'RangeRec.Insert(false)' in s and 'Commit(' not in s)
 ck(name+' uses both From/To and selected rows','.SuggestLines(RangeRec."From Date", RangeRec."To Date")' in s and 'CurrPage.SetSelectionFilter(Worksheet)' in s and '.PostWorksheet(Worksheet)' in s)
ck('No modal calls inside financial writer codeunits','RunModal' not in dep and 'RunModal' not in roy)
ck('Depletion refreshes only same-window unposted drafts','Existing."Period Start" = FromDate' in dep and 'Existing.SetRange(Posted, false)' in dep)
ck('Depletion blocks overlapping posted periods','CheckNoPostedOverlap' in dep and 'overlaps already journalised' in dep)
ck('Depletion stops stale production snapshots','CurrentProduction(Worksheet) - Worksheet."Period Production BOE"' in dep)
ck('Financial auto-increment PKs reset for each new row','Worksheet."Entry No." := 0' in dep and 'Worksheet."Entry No." := 0' in roy)
ck('General Journal uses standard Amount/Account/Dimension validation',all(s in jnl for s in ['Validate(Amount, DebitAmount - CreditAmount)','Validate("Account No.", AccountNo)','Validate("Dimension Set ID", CombinedID)']))
ck('General and item journal lines use full template/batch keys','GenJnlLine."Journal Template Name" := TemplateName' in jnl and 'JournalLine."Journal Template Name" := Setup."Item Journal Template Name"' in roy)
ck('Royalty avoids duplicate source-line journalisation','AlreadyJournalised' in roy and 'Production Document No.' in roy and 'Production Line No.' in roy)
ck('In-kind royalty has positive quantity for Negative Adjmt.','Validate("Entry Type", JournalLine."Entry Type"::"Negative Adjmt.")' in roy and 'Validate(Quantity, Worksheet."Royalty Volume")' in roy and 'Quantity := -' not in roy)
ck('In-kind royalty expense posting group is setup driven','Setup."Royalty Gen. Bus. Post. Group"' in roy and 'PostingSetup.TestField("Inventory Adjmt. Account")' in roy)
ck('Royalty still includes produced water; no exclusion flag','Exclude from Royalty' not in src and 'Line."Net Quantity" * Rate / 100' in roy)
ck('Production reversal does not silently reverse existing financial journals','existing financial journals are not automatically reversed' in roy and 'NOT silently reversed' in rd('src/Pages/ProductionCorrectionDialog.Page.al'))
ck('JV ownership uses an effective-dated version','Ownership.SetFilter("Starting Date", \'..%1\', PostingDate)' in own and 'Ownership.FindLast()' in own)
ck('Explicit operator interest plus members must total 100','Total := Ownership."Operator Interest %"' in own and 'Abs(Total - 100)' in own)
ck('No implicit operator remainder/management-fee allocation','NOT an operator share or management fee' in own and 'OperatorAmount := Round(Line.Amount * Ownership."Operator Interest %"' in jv)
ck('Operator-only Entity rejected by JV allocator','Entity.TestField(Type, Entity.Type::"Joint Operation")' in own)
ck('Existing partner masters reused through ownership membership','Partner.Get(Member."Partner Code")' in jv and 'LoadPartnerDefaults' in own)
ck('Posted ownership versions immutable for normal maintenance','Create a new Starting Date' in rd('src/Tables/JVOwnership.Table.al'))
ck('JV rounding assigned to a configured partner, not phantom operator','Share := PartnerTarget - Allocated' in jv)
ck('Operator future equity cost has explicit Operator Entity','Ownership."Operator Cost Entity"' in jv and 'Operator equity cost reclass' in jv)
for name in ['ProductionEntryList.Page.al','PostedProductionCard.Page.al']:
 s=rd('src/Pages/'+name)
 ck(name+' keeps read-only history and correction actions','Editable = false;' in s and 'CancelPendingJournal' in s and 'ReversePostedProduction' in s and 'LinkLegacyLedger' in s)
fp=rd('src/PermissionSets/FieldOperator.PermissionSet.al');ac=rd('src/PermissionSets/OGAccountant.PermissionSet.al')
ck('Field Operator cannot execute reversal or production posting','codeunit "Production Reversal Mgt."' not in fp and 'codeunit "Post Daily Production"' not in fp)
ck('Posting evidence write access indirect for Accountant','tabledata "Production Posting Link" = Rim' in ac and 'tabledata "Production Ledger Link" = Ri' in ac)
ck('No account deletion introduced in user selector','Estimator.Delete(' not in src and 'Employee.Delete(' not in src)
ck('Setup singleton fix retained','Inserted := Setup.Insert(true)' in rd('src/Pages/OGSetup.Page.al'))
# Mathematics independent of AL execution: inventory and allocation invariants.
ck('BS&W full reversal example: +48 -1152 -48 equals -1152',Decimal(48)-Decimal(1152)-Decimal(48)==-Decimal(1152))
ck('Production + reversal BOE sum to zero',Decimal(1272)+Decimal(-1272)==0)
ck('Current 0% operator / 60+40 partner example allocates all cost',Decimal(10000)*Decimal(0)/100==0 and Decimal(10000)*Decimal(60)/100+Decimal(10000)*Decimal(40)/100==10000)
q=lambda x:x.quantize(Decimal('.01'),rounding=ROUND_HALF_UP)
a=q(Decimal('1')*Decimal('33.33')/100);b=q(Decimal('1')*Decimal('33.33')/100);c=Decimal('1')-a-b
ck('Zero-operator rounding example allocates full 1.00 to partners',a+b+c==1 and c==Decimal('.34'))
# RDLC integrity and signed/cancelled source scope.
rep=rd('src/Reports/ProductionSummary.Report.al');ck('Production Summary filters cancellations and exposes Entity','Cancelled = const(false)' in rep and 'column(EntityCode;' in rep and 'RequestFilterFields = "Entity Code"' in rep)
ns={'r':'http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition'};xml=ET.parse(str(R/'src/Reports/Layouts/ProductionSummary.rdlc'));txt=ET.tostring(xml).decode();defined={x.get('Name') for x in xml.findall('.//r:Field',ns)};used=set(re.findall(r'Fields!([A-Za-z_][A-Za-z0-9_]*)\.Value',txt))
ck('RDLC expressions resolve to dataset fields',used<=defined)
ck('RDLC groups Entity and sums line BOE, not repeated header BOE','Fields!EntityCode.Value' in txt and 'Sum(Fields!BOEQuantity.Value' in txt and 'Sum(Fields!TotalBOE.Value' not in txt)
ck('No explicit COMMIT in correction/worksheet writers',all('Commit(' not in s and 'COMMIT' not in s for s in [rev,track,dep,roy]))
result={'kind':'Static source/schema/logic checks; NOT BC runtime execution','version':'1.0.13.0','al_files':len(als),'numeric_objects':len(objs),'passed':sum(c['pass'] for c in checks),'total':len(checks),'checks':checks}
(V/'source-checks.json').write_text(json.dumps(result,indent=2)+'\n')
for c in checks:print(('PASS ' if c['pass'] else 'FAIL ')+c['check'])
print(f"{result['passed']}/{result['total']} checks; {len(als)} AL files")
sys.exit(0 if result['passed']==result['total'] else 1)
